-- Seed data for platforms
INSERT INTO platforms (id, name, slug) VALUES
(306, 'Satellaview', 'satellaview'),
(339, 'Sega Pico', 'sega-pico'),
(376, 'Epoch Super Cassette Vision', 'epoch-super-cassette-vision'),
(62, 'Atari Jaguar', 'jaguar'),
(150, 'Turbografx-16/PC Engine CD', 'turbografx-16-slash-pc-engine-cd'),
(156, 'Thomson MO5', 'thomson-mo5'),
(148, 'AY-3-8607', 'ay-3-8607'),
(309, 'Evercade', 'evercade'),
(389, 'AirConsole', 'airconsole'),
(112, 'Microcomputer', 'microcomputer--1'),
(41, 'Wii U', 'wiiu'),
(13, 'DOS', 'dos'),
(60, 'Atari 7800', 'atari7800'),
(410, 'Atari Jaguar CD', 'atari-jaguar-cd'),
(127, 'Fairchild Channel F', 'fairchild-channel-f'),
(30, 'Sega 32X', 'sega32'),
(53, 'MSX2', 'msx2'),
(77, 'Sharp X1', 'x1'),
(132, 'Amazon Fire TV', 'amazon-fire-tv'),
(120, 'Neo Geo Pocket Color', 'neo-geo-pocket-color'),
(61, 'Atari Lynx', 'lynx'),
(413, 'Leapster Explorer/LeadPad Explorer', 'leapster-explorer-slash-leadpad-explorer'),
(153, 'Dragon 32/64', 'dragon-32-slash-64'),
(140, 'AY-3-8500', 'ay-3-8500'),
(143, 'AY-3-8760', 'ay-3-8760'),
(154, 'Amstrad PCW', 'amstrad-pcw'),
(167, 'PlayStation 5', 'ps5'),
(70, 'Vectrex', 'vectrex'),
(145, 'AY-3-8603', 'ay-3-8603'),
(87, 'Virtual Boy', 'virtualboy'),
(386, 'Meta Quest 2', 'meta-quest-2'),
(390, 'PlayStation VR2', 'psvr2'),
(477, 'Panasonic Jungle', 'panasonic-jungle'),
(65, 'Atari 8-bit', 'atari8bit'),
(158, 'Commodore CDTV', 'commodore-cdtv'),
(504, 'Uzebox', 'uzebox'),
(165, 'PlayStation VR', 'psvr'),
(94, 'Commodore Plus/4', 'c-plus-4'),
(123, 'WonderSwan Color', 'wonderswan-color'),
(440, 'Visual Memory Unit / Visual Memory System', 'visual-memory-unit-slash-visual-memory-system'),
(128, 'PC Engine SuperGrafx', 'supergrafx'),
(129, 'Texas Instruments TI-99', 'ti-99'),
(89, 'Microvision', 'microvision--1'),
(48, 'PlayStation 4', 'ps4--1'),
(51, 'Family Computer Disk System', 'fds'),
(473, 'Arcadia 2001', 'arcadia-2001'),
(474, 'Gizmondo', 'gizmondo'),
(482, 'Sega CD 32X', 'sega-cd-32x'),
(6, 'PC (Microsoft Windows)', 'win'),
(134, 'Acorn Electron', 'acorn-electron'),
(8, 'PlayStation 2', 'ps2'),
(136, 'Neo Geo CD', 'neo-geo-cd'),
(23, 'Dreamcast', 'dc'),
(35, 'Sega Game Gear', 'gamegear'),
(44, 'Tapwave Zodiac', 'zod'),
(88, 'Odyssey', 'odyssey--1'),
(97, 'PDP-8', 'pdp-8--1'),
(39, 'iOS', 'ios'),
(3, 'Linux', 'linux'),
(373, 'Sinclair ZX81', 'sinclair-zx81'),
(133, 'Odyssey 2 / Videopac G7000', 'odyssey-2-slash-videopac-g7000'),
(135, 'Hyper Neo Geo 64', 'hyper-neo-geo-64'),
(142, 'PC-50X Family', 'pc-50x-family'),
(144, 'AY-3-8710', 'ay-3-8710'),
(146, 'AY-3-8605', 'ay-3-8605'),
(147, 'AY-3-8606', 'ay-3-8606'),
(149, 'PC-9800 Series', 'pc-9800-series'),
(505, 'Elektor TV Games Computer', 'elektor-tv-games-computer'),
(163, 'SteamVR', 'steam-vr'),
(237, 'Sol-20', 'sol-20'),
(85, 'Donner Model 30', 'donner30'),
(24, 'Game Boy Advance', 'gba'),
(78, 'Sega CD', 'segacd'),
(115, 'Apple IIGS', 'apple-iigs'),
(119, 'Neo Geo Pocket', 'neo-geo-pocket'),
(125, 'PC-8800 Series', 'pc-8800-series'),
(72, 'Ouya', 'ouya'),
(101, 'Ferranti Nimrod Computer', 'nimrod'),
(108, 'PDP-11', 'pdp11'),
(506, 'Amstrad GX4000', 'amstrad-gx4000'),
(109, 'CDC Cyber 70', 'cdccyber70'),
(113, 'OnLive Game System', 'onlive-game-system'),
(98, 'DEC GT40', 'gt40'),
(124, 'SwanCrystal', 'swancrystal'),
(138, 'VC 4000', 'vc-4000'),
(139, '1292 Advanced Programmable Video System', '1292-advanced-programmable-video-system'),
(155, 'Tatung Einstein', 'tatung-einstein'),
(46, 'PlayStation Vita', 'psvita'),
(66, 'Atari 5200', 'atari5200'),
(9, 'PlayStation 3', 'ps3'),
(11, 'Xbox', 'xbox'),
(111, 'Imlac PDS-1', 'imlac-pds1'),
(15, 'Commodore C64/128/MAX', 'c64'),
(18, 'Nintendo Entertainment System', 'nes'),
(162, 'Oculus VR', 'oculus-vr'),
(67, 'Intellivision', 'intellivision'),
(20, 'Nintendo DS', 'nds'),
(22, 'Game Boy Color', 'gbc'),
(32, 'Sega Saturn', 'saturn'),
(131, 'Super NES CD-ROM System', 'super-nes-cd-rom-system'),
(73, 'BlackBerry OS', 'blackberry'),
(114, 'Amiga CD32', 'amiga-cd32'),
(116, 'Acorn Archimedes', 'acorn-archimedes'),
(117, 'Philips CD-i', 'philips-cd-i'),
(118, 'FM Towns', 'fm-towns'),
(121, 'Sharp X68000', 'sharp-x68000'),
(152, 'FM-7', 'fm-7'),
(157, 'NEC PC-6000 Series', 'nec-pc-6000-series'),
(86, 'TurboGrafx-16/PC Engine', 'turbografx16--1'),
(307, 'Game & Watch', 'g-and-w'),
(308, 'Playdia', 'playdia'),
(122, 'Nuon', 'nuon'),
(141, 'AY-3-8610', 'ay-3-8610'),
(507, 'Advanced Pico Beena', 'advanced-pico-beena'),
(42, 'N-Gage', 'ngage'),
(170, 'Google Stadia', 'stadia'),
(161, 'Windows Mixed Reality', 'windows-mixed-reality'),
(57, 'WonderSwan', 'wonderswan'),
(69, 'BBC Microcomputer System', 'bbcmicro'),
(71, 'Commodore VIC-20', 'vic-20'),
(74, 'Windows Phone', 'winphone'),
(21, 'Nintendo GameCube', 'ngc'),
(33, 'Game Boy', 'gb'),
(79, 'Neo Geo MVS', 'neogeomvs'),
(80, 'Neo Geo AES', 'neogeoaes'),
(84, 'SG-1000', 'sg1000'),
(91, 'Bally Astrocade', 'astrocade'),
(93, 'Commodore 16', 'c16'),
(479, 'Terebikko / See n Say Video Phone', 'terebikko-slash-see-n-say-video-phone'),
(96, 'PDP-10', 'pdp10'),
(508, 'Nintendo Switch 2', 'nintendo-switch-2'),
(103, 'PDP-7', 'pdp-7--1'),
(38, 'PlayStation Portable', 'psp'),
(137, 'New Nintendo 3DS', 'new-nintendo-3ds'),
(374, 'Sharp MZ-2200', 'sharp-mz-2200'),
(375, 'Epoch Cassette Vision', 'epoch-cassette-vision'),
(377, 'Plug & Play', 'plug-and-play'),
(379, 'Game.com', 'game-dot-com'),
(382, 'Intellivision Amico', 'intellivision-amico'),
(384, 'Oculus Quest', 'oculus-quest'),
(385, 'Oculus Rift', 'oculus-rift'),
(387, 'Oculus Go', 'oculus-go'),
(388, 'Gear VR', 'gear-vr'),
(50, '3DO Interactive Multiplayer', '3do'),
(169, 'Xbox Series X|S', 'series-x-s'),
(64, 'Sega Master System/Mark III', 'sms'),
(151, 'TRS-80 Color Computer', 'trs-80-color-computer'),
(238, 'DVD Player', 'dvd-player'),
(274, 'PC-FX', 'pc-fx'),
(26, 'ZX Spectrum', 'zxs'),
(27, 'MSX', 'msx'),
(37, 'Nintendo 3DS', '3ds'),
(240, 'Zeebo', 'zeebo'),
(95, 'PDP-1', 'pdp1'),
(166, 'Pokémon mini', 'pokemon-mini'),
(203, 'DUPLICATE Stadia', 'duplicate-stadia'),
(110, 'PLATO', 'plato--1'),
(164, 'Daydream', 'daydream'),
(100, 'Analogue electronics', 'analogueelectronics'),
(478, 'Panasonic M2', 'panasonic-m2'),
(236, 'Exidy Sorcerer', 'exidy-sorcerer'),
(102, 'EDSAC', 'edsac--1'),
(104, 'HP 2100', 'hp2100'),
(105, 'HP 3000', 'hp3000'),
(106, 'SDS Sigma 7', 'sdssigma7'),
(107, 'Call-A-Computer time-shared mainframe computer system', 'call-a-computer'),
(239, 'Blu-ray Player', 'blu-ray-player'),
(509, 'Polymega', 'polymega'),
(99, 'Family Computer', 'famicom'),
(486, 'Digiblast', 'digiblast'),
(372, 'OOParts', 'ooparts'),
(378, 'Gamate', 'gamate'),
(380, 'Casio Loopy', 'casio-loopy'),
(381, 'Playdate', 'playdate'),
(411, 'Handheld Electronic LCD', 'handheld-electronic-lcd'),
(415, 'Watara/QuickShot Supervision', 'watara-slash-quickshot-supervision'),
(438, 'Arduboy', 'arduboy'),
(471, 'Meta Quest 3', 'meta-quest-3'),
(7, 'PlayStation', 'ps'),
(16, 'Amiga', 'amiga'),
(439, 'V.Smile', 'vsmile'),
(441, 'PocketStation', 'pocketstation'),
(480, 'Super A''Can', 'super-acan'),
(47, 'Virtual Console', 'vc'),
(52, 'Arcade', 'arcade'),
(59, 'Atari 2600', 'atari2600'),
(472, 'visionOS', 'visionos'),
(12, 'Xbox 360', 'xbox360'),
(68, 'ColecoVision', 'colecovision'),
(25, 'Amstrad CPC', 'acpc'),
(29, 'Sega Mega Drive/Genesis', 'genesis-slash-megadrive'),
(34, 'Android', 'android'),
(475, 'R-Zone', 'r-zone'),
(476, 'Apple Pippin', 'apple-pippin'),
(481, 'Tomy Tutor / Pyuta / Grandstand Tutor', 'tomy-tutor-slash-pyuta-slash-grandstand-tutor'),
(405, 'Windows Mobile', 'windows-mobile'),
(406, 'Sinclair QL', 'sinclair-ql'),
(407, 'HyperScan', 'hyperscan'),
(408, 'Mega Duck/Cougar Boy', 'mega-duck-slash-cougar-boy'),
(409, 'Legacy Computer', 'legacy-computer'),
(412, 'Leapster', 'leapster'),
(414, 'LeapTV', 'leaptv'),
(416, '64DD', '64dd'),
(417, 'Palm OS', 'palm-os'),
(49, 'Xbox One', 'xboxone'),
(55, 'Legacy Mobile Device', 'mobile'),
(58, 'Super Famicom', 'sfam'),
(4, 'Nintendo 64', 'n64'),
(63, 'Atari ST/STE', 'atari-st'),
(75, 'Apple II', 'appleii'),
(82, 'Web browser', 'browser'),
(90, 'Commodore PET', 'cpet'),
(126, 'TRS-80', 'trs-80'),
(159, 'Nintendo DSi', 'nintendo-dsi'),
(5, 'Wii', 'wii'),
(14, 'Mac', 'mac'),
(19, 'Super Nintendo Entertainment System', 'snes'),
(487, 'LaserActive', 'laseractive'),
(130, 'Nintendo Switch', 'switch');

-- Add ON CONFLICT DO NOTHING to handle any duplicates gracefully
-- ON CONFLICT (id) DO NOTHING; 

-- Seed data for genres
INSERT INTO genres (id, name, slug) VALUES
(2, 'Point-and-click', 'point-and-click'),
(4, 'Fighting', 'fighting'),
(5, 'Shooter', 'shooter'),
(7, 'Music', 'music'),
(8, 'Platform', 'platform'),
(9, 'Puzzle', 'puzzle'),
(10, 'Racing', 'racing'),
(11, 'Real Time Strategy (RTS)', 'real-time-strategy-rts'),
(12, 'Role-playing (RPG)', 'role-playing-rpg'),
(13, 'Simulator', 'simulator'),
(14, 'Sport', 'sport'),
(15, 'Strategy', 'strategy'),
(16, 'Turn-based strategy (TBS)', 'turn-based-strategy-tbs'),
(24, 'Tactical', 'tactical'),
(25, 'Hack and slash/Beat ''em up', 'hack-and-slash-beat-em-up'),
(26, 'Quiz/Trivia', 'quiz-trivia'),
(30, 'Pinball', 'pinball'),
(31, 'Adventure', 'adventure'),
(32, 'Indie', 'indie'),
(33, 'Arcade', 'arcade'),
(34, 'Visual Novel', 'visual-novel'),
(35, 'Card & Board Game', 'card-and-board-game'),
(36, 'MOBA', 'moba');

-- Add ON CONFLICT DO NOTHING to handle any duplicates gracefully
-- ON CONFLICT (id) DO NOTHING; 

-- Seed data for game modes
INSERT INTO game_modes (id, name, slug) VALUES
(1, 'Single player', 'single-player'),
(2, 'Multiplayer', 'multiplayer'),
(3, 'Co-operative', 'co-operative'),
(4, 'Split screen', 'split-screen'),
(5, 'Massively Multiplayer Online (MMO)', 'massively-multiplayer-online-mmo'),
(6, 'Battle Royale', 'battle-royale');

-- Add ON CONFLICT DO NOTHING to handle any duplicates gracefully
-- ON CONFLICT (id) DO NOTHING; 

-- Seed data for game types
INSERT INTO game_types (id, type) VALUES
(0, 'Main Game'),
(1, 'DLC Addon'),
(2, 'Expansion'),
(3, 'Bundle'),
(4, 'Standalone Expansion'),
(5, 'Mod'),
(6, 'Episode'),
(7, 'Season'),
(8, 'Remake'),
(9, 'Remaster'),
(10, 'Expanded Game'),
(11, 'Port'),
(12, 'Fork'),
(13, 'Pack'),
(14, 'Update');

-- Add ON CONFLICT DO NOTHING to handle any duplicates gracefully
-- ON CONFLICT (id) DO NOTHING; 

-- Seed data for website types
INSERT INTO website_types (id, type) VALUES
(1, 'official'),
(2, 'wikia'),
(3, 'wikipedia'),
(4, 'facebook'),
(5, 'twitter'),
(6, 'twitch'),
(8, 'instagram'),
(9, 'youtube'),
(10, 'iphone'),
(11, 'ipad'),
(12, 'android'),
(13, 'steam'),
(14, 'reddit'),
(15, 'itch'),
(16, 'epicgames'),
(17, 'gog'),
(18, 'discord'),
(19, 'bluesky');

-- Add ON CONFLICT DO NOTHING to handle any duplicates gracefully
-- ON CONFLICT (id) DO NOTHING; 